# Generated by Django 4.2.4 on 2024-03-27 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractedfile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='login',
            name='user',
        ),
        migrations.DeleteModel(
            name='EncodedImage',
        ),
        migrations.DeleteModel(
            name='ExtractedFile',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
